### ISSUE TITLE
RuntimeError: Encounter error 'The value updated is not the same shape as the original. Updated: (1024, 64, 31), original: (1024, 64, 31, 1)' for parameter 'f5_transformer.input_embed.conv_pos_embed.conv1d1.weight'

### ISSUE THREAD

**Issue by jeremy110** [Bigfishering/f5-tts-trtllm#1]
您好，非常感谢您的程式
我目前照著你的步驟做，但在trtllm-build時會發生維度上的錯誤，想請問是哪裡有問題?
![image](https://github.com/user-attachments/assets/6432ccc9-e5b4-43f5-a998-9b83198f00b7)

另外在model.py裡import .modules ，是不是要將 module.py改成modules.py

**Comment by Bigfishering** [comment]
我想这是环境的问题，nvcr.io/nvidia/pytorch:23.10-py3 你可以通过这个镜像构建环境。

**Comment by jeremy110** [comment]
好的感謝，我試試看

**Comment by jeremy110** [comment]
我尝试使用nvcr.io/nvidia/pytorch:23.10-py3去建构环境，但会卡在无法安装mpi4py，即使我安装所有它需要的套件，所以我想在我原本的环境下使用

想请问是tensorrt-llm 版本影响到维度不同的问题吗? 是否可以询问你的版本为何?

**Comment by kmn1024** [comment]
Same problem...

```...
[12/19/2024-10:35:01] [TRT-LLM] [W] Parameter dtype is None, using default dtype: DataType.HALF, it is recommended to always specify dtype explicitly                                                                                                                 
[12/19/2024-10:35:01] [TRT-LLM] [W] Provided but not expected tensors: {'f5_transformer.text_embed.text_blocks.1.norm.bias', 'f5_transformer.text_embed.text_blocks.1.pwconv1.weight', 'f5_transformer.text_embed.text_blocks.3.norm.weight', 'f5_transformer.text_embed.text_blocks.3.pwconv1.bias', 'f5_transformer.text_embed.text_blocks.1.dwconv.weight', 'f5_transformer.text_embed.text_blocks.0.pwconv2.weight', 'f5_transformer.text_embed.text_blocks.1.norm.weight', 'f5_transformer.text_embed.text_blocks.0.norm.weight', 'f5_transformer.text_embed.text_blocks.1.grn.beta', 'f5_transformer.text_embed.text_blocks.3.grn.gamma', 'f5_transformer.text_embed.text_blocks.1.pwconv2.weight', 'f5_transformer.text_embed.text_blocks.0.norm.bias', 'f5_transformer.text_embed.text_blocks.0.pwconv2.bias', 'f5_transformer.text_embed.text_blocks.2.pwconv1.weight', 'f5_transformer.text_embed.text_blocks.0.pwconv1.weight', 'f5_transformer.text_embed.text_embed.weight', 'f5_transformer.text_embed.text_blocks.3.pwconv2.bias', 'f5_transformer.text_embed.text_blocks.3.dwconv.bias', 'f5_transformer.text_embed.text_blocks.3.pwconv2.weight', 'f5_transformer.text_embed.text_blocks.2.grn.beta', 'f5_transformer.text_embed.text_blocks.1.dwconv.bias', 'f5_transformer.text_embed.text_blocks.0.dwconv.weight', 'f5_transformer.text_embed.text_blocks.3.grn.beta', 'f5_transformer.text_embed.text_blocks.3.dwconv.weight', 'f5_transformer.text_embed.text_blocks.1.pwconv2.bias', 'f5_transformer.text_embed.text_blocks.0.grn.gamma', 'f5_transformer.text_embed.text_blocks.0.grn.beta', 'f5_transformer.text_embed.text_blocks.2.dwconv.bias', 'f5_transformer.text_embed.text_blocks.2.norm.bias', 'f5_transformer.text_embed.text_blocks.3.norm.bias', 'f5_transformer.text_embed.text_blocks.2.norm.weight', 'f5_transformer.text_embed.text_blocks.1.grn.gamma', 'f5_transformer.text_embed.text_blocks.3.pwconv1.weight', 'f5_transformer.text_embed.text_blocks.0.dwconv.bias', 'f5_transformer.text_embed.text_blocks.2.pwconv2.bias', 'f5_transformer.text_embed.text_blocks.2.pwconv2.weight', 'f5_transformer.text_embed.text_blocks.2.dwconv.weight', 'f5_transformer.text_embed.text_blocks.2.pwconv1.bias', 'f5_transformer.text_embed.text_blocks.0.pwconv1.bias', 'f5_transformer.text_embed.text_blocks.1.pwconv1.bias', 'f5_transformer.text_embed.text_blocks.2.grn.gamma', 'f5_transformer.rotary_embed.inv_freq'}                                                                                                                       
Traceback (most recent call last):                                                                                                 
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 673, in load               
    param.value = weights[name]                                                                                                    
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/parameter.py", line 201, in value                          
    assert v.shape == self.shape, \                              
AssertionError: The value updated is not the same shape as the original. Updated: (1024, 64, 31), original: (1024, 64, 31, 1)      
                                                                 
During handling of the above exception, another exception occurred:                                                                
                                                                                                                                   
Traceback (most recent call last):                                                                                                 
  File "/opt/conda/envs/myenv/bin/trtllm-build", line 8, in <module>                                                               
    sys.exit(main())                                                                                                               
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 602, in main                      
    parallel_build(model_config, ckpt_dir, build_config, args.output_dir,                                                          
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 425, in parallel_build            
    passed = build_and_save(rank, rank % workers, ckpt_dir,                                                                        
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 390, in build_and_save            
    engine = build_model(build_config,                                                                                             
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 360, in build_model               
    model = model_cls.from_checkpoint(ckpt_dir, config=rank_config)                                                                
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 648, in from_checkpoint    
    model.load(weights, from_pruned=is_checkpoint_pruned)                                                                          
  File "/opt/conda/envs/myenv/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 675, in load               
    raise RuntimeError(                                                                                                            
RuntimeError: Encounter error 'The value updated is not the same shape as the original. Updated: (1024, 64, 31), original: (1024, 64, 31, 1)' for parameter 'f5_transformer.input_embed.conv_pos_embed.conv1d1.weight'                                                
```

**Comment by Bigfishering** [comment]
> @Bigfishering 想再请问一下，我目前用 pre-trained model 转成 TensorRT 确实可以合成出正常的声音，但我用自己fine-tune 新语言的model 转成 TensorRT 却产生乱念的情况，声音是相似但字乱念 (我确认过text_ids是有对应到我自己加的char)，不知道您有没有遇过类似问题?

出现过，是需要根据你微调的模型的参数，修改前处理的参数重新导出前处理的onnx，前处理的onnx导出过程中涉及到一些模型的参数需要修改

**Comment by jeremy110** [comment]
@Bigfishering 
感谢您的回覆，我有成功导出onnx，的确如你所说差在前处理，现在终于产生对的声音了，十分感谢。

**Comment by jeremy110** [comment]
@Bigfishering
作者您好，不好意思想再请问一下，我想要将model同时load到多GPU，然后给个json档，里面包含reference 音档路径 文字...，去产生大量资料，我尝试使用thread + queue去做，但会遇到Error Code 1: Cuda Runtime (an illegal memory access was encountered)，不确定是哪里出了问题，不知道这方面您是否有经验，或有写类似脚本可以参考?

**Comment by WGS-note** [comment]
@jeremy110 你好大哥，可以分享一下代码吗？不胜感激！

**Comment by jeremy110** [comment]
@WGS-note 
你指的是环境建构的代码吗?
