### ISSUE TITLE
输出品质较pytorch差?

### ISSUE THREAD

**Issue by kmn1024** [Bigfishering/f5-tts-trtllm#3]
请看看附加的两个输出。

请注意，我已经修改了代码，以便两个 Vocos 都使用 pytorch，因此质量差异完全是来自于 F5 TRT

https://github.com/user-attachments/assets/6297a574-63e8-418d-98c2-8bb4bac5ac2e

https://github.com/user-attachments/assets/7e193017-3c45-4936-a2f1-2cf74dfa806b

**Comment by banhongjun** [comment]
@kmn1024您好，问下你生成的环境是docker吗?按照教程进行模型转换，我这边生成的音频是杂音，请问知道怎么解决吗？ 
[gen.zip](https://github.com/user-attachments/files/18237717/gen.zip)

**Comment by kmn1024** [comment]
@banhongjun 我没有用docker. 我用:

apt-get install -y libopenmpi-dev
conda create -n myenv python=3.10
conda activate myenv
pip install torch==2.5.1
pip install tensorrt_llm

**Comment by WGS-note** [comment]
@kmn1024 老哥你好，请问你的 tensorrt_llm 是什么版本的？

请问你遇到过以下错误吗：
```shell
Traceback (most recent call last):
  File "/home/wangguisen/projects/tts/trtllm_f5tts/f5tts/sample.py", line 414, in <module>
    main(args)
  File "/home/wangguisen/projects/tts/trtllm_f5tts/f5tts/sample.py", line 383, in main
    model = F5TTS(config, debug_mode=args.debug_mode)
  File "/home/wangguisen/projects/tts/trtllm_f5tts/f5tts/sample.py", line 236, in __init__
    self.session = Session.from_serialized_engine(engine_buffer)
  File "/home/wangguisen/miniconda3/envs/f5_tts_trtllm/lib/python3.10/site-packages/tensorrt_llm/runtime/session.py", line 87, in from_serialized_engine
    return session._init(engine)
  File "/home/wangguisen/miniconda3/envs/f5_tts_trtllm/lib/python3.10/site-packages/tensorrt_llm/runtime/session.py", line 69, in _init
    if not self.engine.streamable_weights_size:
AttributeError: 'NoneType' object has no attribute 'streamable_weights_size'
```

**Comment by kmn1024** [comment]
@WGS-note  0.15.0

**Comment by lq0104** [comment]
请问后来有新的尝试么，TRT的质量有所提升吗？

**Comment by kmn1024** [comment]
不要使用 preprocess onnx，直接调用 pytorch 代码，质量就会很好

在 nvidia 硬件上，preprocess onnx 并不比 pytorch 代码快
